### ISSUE TITLE
Carry the value of previous input onto next step

### ISSUE THREAD

**Issue by avazkhan2808** [ivan-dalmet/formiz#18]
I was wondering if it's possible to carry the value of previous input onto the next step's input field as default value? I tried: 

`defaultValue={ myForm.values.name ]` - This doesn't work
`defaultValue="Some value here"`  - This does work

**Comment by ivan-dalmet** [comment]
Hey 🙂
It doesn't work because all fields are registered at the start with the `defaultValue` and at this point the `myForm.values.name` is `null`.
You can try 1 of these solutions to make it works:

## With conditional rendering
```
Only render the field if the user has visited the step
...
{(myForm.steps.find(x => x.name === 'step2') || {}).isVisited && 
  <Field name="yourField" defaultValue={ myForm.values.name } />
}
...
```

## With Key
Add a key on your field `<Field name="yourField" defaultValue={ myForm.values.name } key={myForm.values.name} />` so **every time** the `myForm.values.name` change the Field will be reset with the correct defaultValue

If you don't want the value to change after the user has visited the step2 you can update the code like that
```
const isVisited = (myForm.steps.find(x => x.name === 'step2') || {}).isVisited;
...
<Field name="yourField" defaultValue={myForm.values.name } key={isVisited || myForm.values.name} />
```

## With setFieldsValues on name change
Update the value on the name change
```
<Field 
  name="name" 
  onChange={(value) => myForm.setFieldsValues({ yourField: value })}  
/>
```

If you don't want the value to change after the user has visited the step2 you can update the code like that
```
const isVisited = (myForm.steps.find(x => x.name === 'step2') || {}).isVisited;
...
<Field 
  name="name" 
  onChange={(value) => !isVisited && myForm.setFieldsValues({ yourField: value })}  
/>
```

---

Tell me if it helps 😊

**Comment by avazkhan2808** [comment]
Hey, thanks for fast reply. I used `setFieldsValues` option and worked like a charm. Thanks for this awesome yet so simple to use tool
